### ISSUE TITLE
500mbps(kong 78mb/s →asvio 36mb/s)

### ISSUE THREAD

**Issue by SQ528** [asvio/R7800-nss#1]
### Describe the bug

Hi, bro.
![Screenshot_20240721_014401_Petal Speed](https://github.com/user-attachments/assets/2abe3015-c002-4b49-98a5-c5f21bfd2244)
I tested your firmware and wifi is only half the speed?

### OpenWrt version

.

### OpenWrt target/subtarget

.

### Device

.

### Image kind

Self-built image

### Steps to reproduce

.

### Actual behaviour

.

### Expected behaviour

.

### Additional info

.

### Diffconfig

```text
.
```

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by asvio** [comment]
I know the problem exit.
Look at
https://forum.openwrt.org/t/ipq806x-nss-build-netgear-r7800-tp-link-c2600-linksys-ea8500/82525/4530

**Comment by SQ528** [comment]
Hello, do you have any solutions?
The thing is this, kong's network disk has updated the 5.15.162 firmware, but the kmod plugin I need is missing from his firmware network disk, and his GitHub has not been updated. I just saw you say in the forum that you have released 23.05.4, so I tested it and found that the network speed is only half.

**Comment by asvio** [comment]
My 23.05 branch is now patched and you will get all the speed device has

**Comment by SQ528** [comment]
Thanks, this Sunday I can try!🫶
2024.7.27 very nice！
